version: '3.9'

networks:
  my_network:
    driver: bridge

services:
  mysql:
    image: mysql:8
    platform: linux/x86_64
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - almabike_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=almabike
      - MYSQL_USER=almabike
      - MYSQL_DATABASE=almabike_db
    networks:
      - my_network
  phpmyadmin:
    hostname: almabike_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:5.1
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST : mysql
    networks:
      - my_network
  api:
    hostname: almabike_api
    depends_on:
      - mysql
    image: v4l3rio/api
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - my_network


volumes:
  almabike_db:
    external: false



